function meta = gainMetadata()
%GAINMETADATA Descriptions of every user gain field (drives GUI field generation).
%
% Inputs:
%   (none)
% Outputs:
%   meta - struct with fields robust, adaptive, baseline; each an Nx5 cell
%          {field, label, units, n_elements, description}                [mixed]

%% ===== Robust SMC =====
smc = { ...
  'lambda_diag', 'Lambda (surface slope)', '1/s',   3, 'Diagonal sliding-surface slope; q_ev converges at Lambda/2 on the surface'; ...
  'K_diag',      'K (s feedback)',          'N*m*s', 3, 'Diagonal linear feedback gain on the sliding variable s'; ...
  'eta',         'eta (switching gain)',    'N*m',   3, 'Switching gain; must exceed the unmodelled torque bound'; ...
  'phi',         'phi (boundary layer)',    'rad/s', 3, 'Boundary-layer thickness of the saturated switching term'};
meta = struct();
meta.robust = smc;

%% ===== Adaptive SMC =====
meta.adaptive = [smc; { ...
  'Gamma_diag',           'Gamma (adaptation gain)', 'kg*m^2*s^2', 6, 'Diagonal adaptation gain of theta_hat_dot = -Gamma*Y''*s'; ...
  'theta_hat0_from_Jnom', 'Start estimate at J_nom', '-',          1, '1 = theta_hat(0) from J_nom, 0 = use theta_hat0'; ...
  'theta_hat0',           'theta_hat(0)',            'kg*m^2',     6, 'Initial estimate [Jxx Jyy Jzz Jxy Jxz Jyz] when the flag is 0'; ...
  'proj_frac',            'Projection fraction',     '-',          1, 'Half-width of the projection box as a fraction of the nominal values'; ...
  'freeze_on_sat',        'Freeze on saturation',    '-',          1, '1 = hold theta_hat while the torque command or a wheel momentum is saturated (adaptation anti-windup)'}];

%% ===== PD benchmark =====
meta.baseline = { ...
  'Kp_diag', 'Kp (proportional)', 'N*m',   3, 'Diagonal proportional gain on the error-quaternion vector part'; ...
  'Kd_diag', 'Kd (derivative)',   'N*m*s', 3, 'Diagonal derivative gain on the rate error'};
end
