function list = listScenarios()
%LISTSCENARIOS Registry of predefined scenario functions and their display names.
%
% Inputs:
%   (none)
% Outputs:
%   list - cell [Kx2], {func_name, display_name}                         [-]

list = { ...
  'scn_nominal',                    'Nominal docking approach'; ...
  'scn_inertia_uncertainty_pm25',   'Inertia uncertainty +-25%'; ...
  'scn_large_attitude_error',       'Large attitude error (150 deg)'; ...
  'scn_disturbance_stress',         'Disturbance stress (4x, all sources)'; ...
  'scn_actuator_saturation_stress', 'Actuator saturation stress'; ...
  'scn_sensor_noise',               'Sensor noise'; ...
  'scn_adaptive_excitation_scan',   'Adaptive showcase: PE attitude scan'};
end
